package hybridcraft.common.mod.init;

import hybridcraft.common.handlers.IDHandler;
import hybridcraft.common.managers.HybridizingManager;
import hybridcraft.common.mod.lib.ItemHybridAxe;
import hybridcraft.common.mod.lib.ItemHybridHoe;
import hybridcraft.common.mod.lib.ItemHybridPickaxe;
import hybridcraft.common.mod.lib.ItemHybridSpade;
import hybridcraft.common.mod.lib.ItemHybridSword;
import net.minecraft.src.Item;
import net.minecraft.src.ItemStack;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class Tools {
	
	public static Item dirtSword;
	public static Item dirtPick;
	public static Item dirtAxe;
	public static Item dirtShovel;
	public static Item dirtHoe;
	public static Item dirtoneSword;
	public static Item dirtonePick;
	public static Item dirtoneAxe;
	public static Item dirtoneShovel;
	public static Item dirtoneHoe;
	public static Item dironSword;
	public static Item dironPick;
	public static Item dironAxe;
	public static Item dironShovel;
	public static Item dironHoe;
	public static Item diroldSword;
	public static Item diroldPick;
	public static Item diroldAxe;
	public static Item diroldShovel;
	public static Item diroldHoe;
	public static Item dirmendSword;
	public static Item dirmendPick;
	public static Item dirmendAxe;
	public static Item dirmendShovel;
	public static Item dirmendHoe;
	public static Item stornSword;
	public static Item stornPick;
	public static Item stornAxe;
	public static Item stornShovel;
	public static Item stornHoe;
	public static Item stoldSword;
	public static Item stoldPick;
	public static Item stoldAxe;
	public static Item stoldShovel;
	public static Item stoldHoe;
	public static Item stomendSword;
	public static Item stomendPick;
	public static Item stomendAxe;
	public static Item stomendShovel;
	public static Item stomendHoe;
	public static Item iroldSword;
	public static Item iroldPick;
	public static Item iroldAxe;
	public static Item iroldShovel;
	public static Item iroldHoe;
	public static Item irmendSword;
	public static Item irmendPick;
	public static Item irmendAxe;
	public static Item irmendShovel;
	public static Item irmendHoe;
	public static Item gomendSword;
	public static Item gomendPick;
	public static Item gomendAxe;
	public static Item gomendShovel;
	public static Item gomendHoe;
	public static Item obsidianSword;
	public static Item obsidianPick;
	public static Item obsidianAxe;
	public static Item obsidianShovel;
	public static Item obsidianHoe;
	public static Item sandSword;
	public static Item sandPick;
	public static Item sandAxe;
	public static Item sandShovel;
	public static Item sandHoe;
	public static Item cobbleSword;
	public static Item cobblePick;
	public static Item cobbleAxe;
	public static Item cobbleShovel;
	public static Item cobbleHoe;
	public static Item emeraldSword;
	public static Item emeraldPick;
	public static Item emeraldAxe;
	public static Item emeraldShovel;
	public static Item emeraldHoe;
	
	
	public static void initItems()
	{
		// Tools
		dirtSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.DIRT_SWORD, hybridcraft.common.handlers.MaterialHandler.dirt).setIconIndex(0).setItemName("dirtSword");
		dirtPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.DIRT_PICK, hybridcraft.common.handlers.MaterialHandler.dirt).setIconIndex(1).setItemName("dirtPick");
		dirtAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.DIRT_AXE, hybridcraft.common.handlers.MaterialHandler.dirt).setIconIndex(2).setItemName("dirtAxe");
		dirtShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.DIRT_SHOVEL, hybridcraft.common.handlers.MaterialHandler.dirt).setIconIndex(3).setItemName("dirtShovel");
		dirtHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.DIRT_HOE, hybridcraft.common.handlers.MaterialHandler.dirt).setIconIndex(4).setItemName("dirtHoe");
		dirtoneSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.DIRTONE_SWORD, hybridcraft.common.handlers.MaterialHandler.dirtone).setIconIndex(5).setItemName("dirtoneSword");
		dirtonePick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.DIRTONE_PICK, hybridcraft.common.handlers.MaterialHandler.dirtone).setIconIndex(6).setItemName("dirtonePick");
		dirtoneAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.DIRTONE_AXE, hybridcraft.common.handlers.MaterialHandler.dirtone).setIconIndex(7).setItemName("dirtoneAxe");
		dirtoneShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.DIRTONE_SHOVEL, hybridcraft.common.handlers.MaterialHandler.dirtone).setIconIndex(8).setItemName("dirtoneShovel");
		dirtoneHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.DIRTONE_HOE, hybridcraft.common.handlers.MaterialHandler.dirtone).setIconIndex(9).setItemName("dirtoneHoe");
		dironSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.DIRTONE_SWORD, hybridcraft.common.handlers.MaterialHandler.dirtone).setIconIndex(10).setItemName("dironSword");
		dironPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.DIRON_PICK, hybridcraft.common.handlers.MaterialHandler.diron).setIconIndex(11).setItemName("dironPick");
		dironAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.DIRON_AXE, hybridcraft.common.handlers.MaterialHandler.diron).setIconIndex(12).setItemName("dironAxe");
		dironShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.DIRON_SHOVEL,hybridcraft.common.handlers.MaterialHandler. diron).setIconIndex(13).setItemName("dironShovel");
		dironHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.DIRON_HOE, hybridcraft.common.handlers.MaterialHandler.diron).setIconIndex(14).setItemName("dironHoe");
		diroldSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.DIROLD_SWORD, hybridcraft.common.handlers.MaterialHandler.dirold).setIconIndex(15).setItemName("diroldSword");
		diroldPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.DIROLD_PICK, hybridcraft.common.handlers.MaterialHandler.dirold).setIconIndex(16).setItemName("diroldPick");
		diroldAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.DIROLD_AXE, hybridcraft.common.handlers.MaterialHandler.dirold).setIconIndex(17).setItemName("diroldAxe");
		diroldShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.DIROLD_SHOVEL, hybridcraft.common.handlers.MaterialHandler.dirold).setIconIndex(18).setItemName("diroldShovel");
		diroldHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.DIROLD_HOE, hybridcraft.common.handlers.MaterialHandler.dirold).setIconIndex(19).setItemName("diroldHoe");
		dirmendSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.DIRMEND_SWORD, hybridcraft.common.handlers.MaterialHandler.dirmend).setIconIndex(20).setItemName("dirmendSword");
		dirmendPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.DIRMEND_PICK, hybridcraft.common.handlers.MaterialHandler.dirmend).setIconIndex(21).setItemName("dirmendPick");
		dirmendAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.DIRMEND_AXE, hybridcraft.common.handlers.MaterialHandler.dirmend).setIconIndex(22).setItemName("dirmendAxe");
		dirmendShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.DIRMEND_SHOVEL, hybridcraft.common.handlers.MaterialHandler.dirmend).setIconIndex(23).setItemName("dirmendShovel");
		dirmendHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.DIRMEND_HOE, hybridcraft.common.handlers.MaterialHandler.irmend).setIconIndex(24).setItemName("dirmendHoe");
		stornSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.STORN_SWORD, hybridcraft.common.handlers.MaterialHandler.storn).setIconIndex(25).setItemName("stornSword");
		stornPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.STORN_PICK, hybridcraft.common.handlers.MaterialHandler.storn).setIconIndex(26).setItemName("stornPick");
		stornAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.STORN_AXE, hybridcraft.common.handlers.MaterialHandler.storn).setIconIndex(27).setItemName("stornAxe");
		stornShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.STORN_SHOVEL, hybridcraft.common.handlers.MaterialHandler.storn).setIconIndex(28).setItemName("stornShovel");
		stornHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.STORN_HOE, hybridcraft.common.handlers.MaterialHandler.storn).setIconIndex(29).setItemName("stornHoe");
		stoldSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.STOLD_SWORD, hybridcraft.common.handlers.MaterialHandler.stold).setIconIndex(30).setItemName("stoldSword");
		stoldPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.STOLD_PICK, hybridcraft.common.handlers.MaterialHandler.stold).setIconIndex(31).setItemName("stoldPick");
		stoldAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.STOLD_AXE, hybridcraft.common.handlers.MaterialHandler.stold).setIconIndex(32).setItemName("stoldAxe");
		stoldShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.STOLD_SHOVEL, hybridcraft.common.handlers.MaterialHandler.stold).setIconIndex(33).setItemName("stoldShovel");
		stoldHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.STOLD_HOE, hybridcraft.common.handlers.MaterialHandler.stold).setIconIndex(34).setItemName("stoldHoe");
		stomendSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.STOMEND_SWORD, hybridcraft.common.handlers.MaterialHandler.stomend).setIconIndex(35).setItemName("stomendSword");
		stomendPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.STOMEND_PICK, hybridcraft.common.handlers.MaterialHandler.stomend).setIconIndex(36).setItemName("stomendPick");
		stomendAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.STOMEND_AXE, hybridcraft.common.handlers.MaterialHandler.stomend).setIconIndex(37).setItemName("stomendAxe");
		stomendShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.STOMEND_SHOVEL, hybridcraft.common.handlers.MaterialHandler.stomend).setIconIndex(38).setItemName("stomendShovel");
		stomendHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.STOMEND_HOE, hybridcraft.common.handlers.MaterialHandler.stomend).setIconIndex(39).setItemName("stomendHoe");
		iroldSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.IROLD_SWORD, hybridcraft.common.handlers.MaterialHandler.irold).setIconIndex(40).setItemName("iroldSword");
		iroldPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.IROLD_PICK, hybridcraft.common.handlers.MaterialHandler.irold).setIconIndex(41).setItemName("iroldPick");
		iroldAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.IROLD_AXE, hybridcraft.common.handlers.MaterialHandler.irold).setIconIndex(42).setItemName("iroldAxe");
		iroldShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.IROLD_SHOVEL, hybridcraft.common.handlers.MaterialHandler.irold).setIconIndex(43).setItemName("iroldShovel");
		iroldHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.IROLD_HOE, hybridcraft.common.handlers.MaterialHandler.irold).setIconIndex(44).setItemName("iroldHoe");
		irmendSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.IRMEND_SWORD, hybridcraft.common.handlers.MaterialHandler.irmend).setIconIndex(45).setItemName("irmendSword");
		irmendPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.IRMEND_PICK, hybridcraft.common.handlers.MaterialHandler.irmend).setIconIndex(46).setItemName("irmendPick");
		irmendAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.IRMEND_AXE, hybridcraft.common.handlers.MaterialHandler.irmend).setIconIndex(47).setItemName("irmendAxe");
		irmendShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.IRMEND_SHOVEL, hybridcraft.common.handlers.MaterialHandler.irmend).setIconIndex(48).setItemName("irmendShovel");
		irmendHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.IRMEND_HOE, hybridcraft.common.handlers.MaterialHandler.irmend).setIconIndex(49).setItemName("irmendHoe");
		gomendSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.GOMEND_SWORD, hybridcraft.common.handlers.MaterialHandler.gomend).setIconIndex(50).setItemName("gomendSword");
		gomendPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.GOMEND_PICK, hybridcraft.common.handlers.MaterialHandler.gomend).setIconIndex(51).setItemName("gomendPick");
		gomendAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.GOMEND_AXE, hybridcraft.common.handlers.MaterialHandler.gomend).setIconIndex(52).setItemName("gomendAxe");
		gomendShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.GOMEND_SHOVEL, hybridcraft.common.handlers.MaterialHandler.gomend).setIconIndex(53).setItemName("gomendShovel");
		gomendHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.GOMEND_HOE, hybridcraft.common.handlers.MaterialHandler.gomend).setIconIndex(54).setItemName("gomendHoe");
		obsidianSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.OBSIDIAN_SWORD, hybridcraft.common.handlers.MaterialHandler.obsidian).setIconIndex(55).setItemName("obsidianSword");
		obsidianPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.OBSIDIAN_PICK, hybridcraft.common.handlers.MaterialHandler.obsidian).setIconIndex(56).setItemName("obsidianPick");
		obsidianAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.OBSIDIAN_AXE, hybridcraft.common.handlers.MaterialHandler.obsidian).setIconIndex(57).setItemName("obsidianAxe");
		obsidianShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.OBSIDIAN_SHOVEL, hybridcraft.common.handlers.MaterialHandler.obsidian).setIconIndex(58).setItemName("obsidianShovel");
		obsidianHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.OBSIDIAN_HOE, hybridcraft.common.handlers.MaterialHandler.obsidian).setIconIndex(59).setItemName("obsidianHoe");
		sandSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.SAND_SWORD, hybridcraft.common.handlers.MaterialHandler.sand).setIconIndex(60).setItemName("sandSword");
		sandPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.SAND_PICK, hybridcraft.common.handlers.MaterialHandler.sand).setIconIndex(61).setItemName("sandPick");
		sandAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.SAND_AXE, hybridcraft.common.handlers.MaterialHandler.sand).setIconIndex(62).setItemName("sandAxe");
		sandShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.SAND_SHOVEL, hybridcraft.common.handlers.MaterialHandler.sand).setIconIndex(63).setItemName("sandShovel");
		sandHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.SAND_HOE, hybridcraft.common.handlers.MaterialHandler.sand).setIconIndex(64).setItemName("sandHoe");
		emeraldSword = new ItemHybridSword(hybridcraft.common.handlers.IDHandler.EMERALD_SWORD, hybridcraft.common.handlers.MaterialHandler.emerald).setIconIndex(70).setItemName("emeraldSword");
		emeraldPick = new ItemHybridPickaxe(hybridcraft.common.handlers.IDHandler.EMERALD_PICK, hybridcraft.common.handlers.MaterialHandler.emerald).setIconIndex(71).setItemName("emeraldPick");
		emeraldAxe = new ItemHybridAxe(hybridcraft.common.handlers.IDHandler.EMERALD_AXE, hybridcraft.common.handlers.MaterialHandler.emerald).setIconIndex(72).setItemName("emeraldAxe");
		emeraldShovel = new ItemHybridSpade(hybridcraft.common.handlers.IDHandler.EMERALD_SHOVEL, hybridcraft.common.handlers.MaterialHandler.emerald).setIconIndex(73).setItemName("emeraldShovel");
		emeraldHoe = new ItemHybridHoe(hybridcraft.common.handlers.IDHandler.EMERALD_HOE, hybridcraft.common.handlers.MaterialHandler.emerald).setIconIndex(74).setItemName("emeraldHoe");
		
		// Tool Registry
		LanguageRegistry.addName(dirtSword, "Dirt Sword");
		LanguageRegistry.addName(dirtPick, "Dirt Pickaxe");
		LanguageRegistry.addName(dirtAxe, "Dirt Axe");
		LanguageRegistry.addName(dirtShovel, "Dirt Shovel");
		LanguageRegistry.addName(dirtHoe, "Dirt Hoe");
		LanguageRegistry.addName(dirtoneSword, "Dirtone Sword");
		LanguageRegistry.addName(dirtonePick, "Dirtone Pickaxe");
		LanguageRegistry.addName(dirtoneAxe, "Dirtone Axe");
		LanguageRegistry.addName(dirtoneShovel, "Dirtone Shovel");
		LanguageRegistry.addName(dirtoneHoe, "Dirtone Hoe");
		LanguageRegistry.addName(dironSword, "Diron Sword");
		LanguageRegistry.addName(dironPick, "Diron Pickaxe");
		LanguageRegistry.addName(dironAxe, "Diron Axe");
		LanguageRegistry.addName(dironShovel, "Diron Shovel");
		LanguageRegistry.addName(dironHoe, "Diron Hoe");
		LanguageRegistry.addName(diroldSword, "Dirold Sword");
		LanguageRegistry.addName(diroldPick, "Dirold Pickaxe");
		LanguageRegistry.addName(diroldAxe, "Dirold Axe");
		LanguageRegistry.addName(diroldShovel, "Dirold Shovel");
		LanguageRegistry.addName(diroldHoe, "Dirold Hoe");
		LanguageRegistry.addName(dirmendSword, "Dirmend Sword");
		LanguageRegistry.addName(dirmendPick, "Dirmend Pickaxe");
		LanguageRegistry.addName(dirmendAxe, "Dirmend Axe");
		LanguageRegistry.addName(dirmendShovel, "Dirmend Shovel");
		LanguageRegistry.addName(dirmendHoe, "Dirmend Hoe");
		LanguageRegistry.addName(stornSword, "Storn Sword");
		LanguageRegistry.addName(stornPick, "Storn Pickaxe");
		LanguageRegistry.addName(stornAxe, "Storn Axe");
		LanguageRegistry.addName(stornShovel, "Storn Shovel");
		LanguageRegistry.addName(stornHoe, "Storn Hoe");
		LanguageRegistry.addName(stoldSword, "Stold Sword");
		LanguageRegistry.addName(stoldPick, "Stold Pickaxe");
		LanguageRegistry.addName(stoldAxe, "Stold Axe");
		LanguageRegistry.addName(stoldShovel, "Stold Shovel");
		LanguageRegistry.addName(stoldHoe, "Stold Hoe");
		LanguageRegistry.addName(stomendSword, "Stomend Sword");
		LanguageRegistry.addName(stomendPick, "Stomend Pickaxe");
		LanguageRegistry.addName(stomendAxe, "Stomend Axe");
		LanguageRegistry.addName(stomendShovel, "Stomend Shovel");
		LanguageRegistry.addName(stomendHoe, "Stomend Hoe");
		LanguageRegistry.addName(iroldSword, "Irold Sword");
		LanguageRegistry.addName(iroldPick, "Irold Pickaxe");
		LanguageRegistry.addName(iroldAxe, "Irold Axe");
		LanguageRegistry.addName(iroldShovel, "Irold Shovel");
		LanguageRegistry.addName(iroldHoe, "Irold Hoe");
		LanguageRegistry.addName(irmendSword, "Irmend Sword");
		LanguageRegistry.addName(irmendPick, "Irmend Pickaxe");
		LanguageRegistry.addName(irmendAxe, "Irmend Axe");
		LanguageRegistry.addName(irmendShovel, "Irmend Shovel");
		LanguageRegistry.addName(irmendHoe, "Irmend Hoe");
		LanguageRegistry.addName(gomendSword, "Gomend Sword");
		LanguageRegistry.addName(gomendPick, "Gomend Pickaxe");
		LanguageRegistry.addName(gomendAxe, "Gomend Axe");
		LanguageRegistry.addName(gomendShovel, "Gomend Shovel");
		LanguageRegistry.addName(gomendHoe, "Gomend Hoe");
		LanguageRegistry.addName(obsidianSword, "Obsidian Sword");
		LanguageRegistry.addName(obsidianPick, "Obsidian Pickaxe");
		LanguageRegistry.addName(obsidianAxe, "Obsidian Axe");
		LanguageRegistry.addName(obsidianShovel, "Obsidian Shovel");
		LanguageRegistry.addName(obsidianHoe, "Obsidian Hoe");
		LanguageRegistry.addName(sandSword, "Sand Sword");
		LanguageRegistry.addName(sandPick, "Sand Pickaxe");
		LanguageRegistry.addName(sandAxe, "Sand Axe");
		LanguageRegistry.addName(sandShovel, "Sand Shovel");
		LanguageRegistry.addName(sandHoe, "Sand Hoe");
		LanguageRegistry.addName(emeraldSword, "Emerald Sword");
		LanguageRegistry.addName(emeraldPick, "Emerald Pickaxe");
		LanguageRegistry.addName(emeraldAxe, "Emerald Axe");
		LanguageRegistry.addName(emeraldShovel, "Emerald Shovel");
		LanguageRegistry.addName(emeraldHoe, "Emerald Hoe");
	}
	
	public static void initRecipies()
	{
		GameRegistry.addRecipe(new ItemStack(dirtSword), new Object[] { "X", "X", "Z", 'X', Ingots.dirtIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirtPick), new Object[] { "XXX", " S ", " S ", 'X', Ingots.dirtIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirtAxe), new Object[] { "XX ", "XS ", " S ", 'X', Ingots.dirtIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirtShovel), new Object[] { "X", "S", "S", 'X', Ingots.dirtIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirtHoe), new Object[] { "XX ", " S ", " S ", 'X', Ingots.dirtIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirtoneSword), new Object[] { "X", "X", "Z", 'X', HybridizingManager.getInstance().dirtoneIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirtonePick), new Object[] { "XXX", " S ", " S ", 'X', HybridizingManager.getInstance().dirtoneIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirtoneAxe), new Object[] { "XX ", "XS ", " S ", 'X', HybridizingManager.getInstance().dirtoneIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirtoneShovel), new Object[] { "X", "S", "S", 'X', HybridizingManager.getInstance().dirtoneIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirtoneHoe), new Object[] { "XX ", " S ", " S ", 'X', HybridizingManager.getInstance().dirtoneIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dironSword), new Object[] { "X", "X", "Z", 'X', HybridizingManager.getInstance().dironIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dironPick), new Object[] { "XXX", " S ", " S ", 'X', HybridizingManager.getInstance().dironIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dironAxe), new Object[] { "XX ", "XS ", " S ", 'X', HybridizingManager.getInstance().dironIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dironShovel), new Object[] { "X", "S", "S", 'X', HybridizingManager.getInstance().dironIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dironHoe), new Object[] { "XX ", " S ", " S ", 'X', HybridizingManager.getInstance().dironIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(diroldSword), new Object[] { "X", "X", "Z", 'X', HybridizingManager.getInstance().diroldIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(diroldPick), new Object[] { "XXX", " S ", " S ", 'X', HybridizingManager.getInstance().diroldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(diroldAxe), new Object[] { "XX ", "XS ", " S ", 'X', HybridizingManager.getInstance().diroldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(diroldShovel), new Object[] { "X", "S", "S", 'X', HybridizingManager.getInstance().diroldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(diroldHoe), new Object[] { "XX ", " S ", " S ", 'X', HybridizingManager.getInstance().diroldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirmendSword), new Object[] { "X", "X", "Z", 'X', HybridizingManager.getInstance().dirmendIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirmendPick), new Object[] { "XXX", " S ", " S ", 'X', HybridizingManager.getInstance().dirmendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirmendAxe), new Object[] { "XX ", "XS ", " S ", 'X', HybridizingManager.getInstance().dirmendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirmendShovel), new Object[] { "X", "S", "S", 'X', HybridizingManager.getInstance().dirmendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(dirmendHoe), new Object[] { "XX ", " S ", " S ", 'X', HybridizingManager.getInstance().dirmendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stornSword), new Object[] { "X", "X", "Z", 'X', HybridizingManager.getInstance().stornIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stornPick), new Object[] { "XXX", " S ", " S ", 'X', HybridizingManager.getInstance().stornIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stornAxe), new Object[] { "XX ", "XS ", " S ", 'X', HybridizingManager.getInstance().stornIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stornShovel), new Object[] { "X", "S", "S", 'X', HybridizingManager.getInstance().stornIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stornHoe), new Object[] { "XX ", " S ", " S ", 'X', HybridizingManager.getInstance().stornIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stoldSword), new Object[] { "X", "X", "Z", 'X', HybridizingManager.getInstance().stoldIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stoldPick), new Object[] { "XXX", " S ", " S ", 'X', HybridizingManager.getInstance().stoldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stoldAxe), new Object[] { "XX ", "XS ", " S ", 'X', HybridizingManager.getInstance().stoldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stoldShovel), new Object[] { "X", "S", "S", 'X', HybridizingManager.getInstance().stoldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stoldHoe), new Object[] { "XX ", " S ", " S ", 'X', HybridizingManager.getInstance().stoldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stomendSword), new Object[] { "X", "X", "Z", 'X', HybridizingManager.getInstance().stomendIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stomendPick), new Object[] { "XXX", " S ", " S ", 'X', HybridizingManager.getInstance().stomendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stomendAxe), new Object[] { "XX ", "XS ", " S ", 'X', HybridizingManager.getInstance().stomendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stomendShovel), new Object[] { "X", "S", "S", 'X', HybridizingManager.getInstance().stomendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(stomendHoe), new Object[] { "XX ", " S ", " S ", 'X', HybridizingManager.getInstance().stomendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(iroldSword), new Object[] { "X", "X", "Z", 'X', HybridizingManager.getInstance().iroldIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(iroldPick), new Object[] { "XXX", " S ", " S ", 'X', HybridizingManager.getInstance().iroldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(iroldAxe), new Object[] { "XX ", "XS ", " S ", 'X', HybridizingManager.getInstance().iroldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(iroldShovel), new Object[] { "X", "S", "S", 'X', HybridizingManager.getInstance().iroldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(iroldHoe), new Object[] { "XX ", " S ", " S ", 'X', HybridizingManager.getInstance().iroldIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(irmendSword), new Object[] { "X", "X", "Z", 'X', HybridizingManager.getInstance().irmendIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(irmendPick), new Object[] { "XXX", " S ", " S ", 'X', HybridizingManager.getInstance().irmendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(irmendAxe), new Object[] { "XX ", "XS ", " S ", 'X', HybridizingManager.getInstance().irmendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(irmendShovel), new Object[] { "X", "S", "S", 'X', HybridizingManager.getInstance().irmendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(irmendHoe), new Object[] { "XX ", " S ", " S ", 'X', HybridizingManager.getInstance().irmendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(gomendSword), new Object[] { "X", "X", "Z", 'X', HybridizingManager.getInstance().gomendIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(gomendPick), new Object[] { "XXX", " S ", " S ", 'X', HybridizingManager.getInstance().gomendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(gomendAxe), new Object[] { "XX ", "XS ", " S ", 'X', HybridizingManager.getInstance().gomendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(gomendShovel), new Object[] { "X", "S", "S", 'X', HybridizingManager.getInstance().gomendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(gomendHoe), new Object[] { "XX ", " S ", " S ", 'X', HybridizingManager.getInstance().gomendIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(obsidianSword), new Object[] { "X", "X", "Z", 'X', Ingots.obsidianIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(obsidianPick), new Object[] { "XXX", " S ", " S ", 'X', Ingots.obsidianIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(obsidianAxe), new Object[] { "XX ", "XS ", " S ", 'X', Ingots.obsidianIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(obsidianShovel), new Object[] { "X", "S", "S", 'X', Ingots.obsidianIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(obsidianHoe), new Object[] { "XX ", " S ", " S ", 'X', Ingots.obsidianIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(sandSword), new Object[] { "X", "X", "Z", 'X', Ingots.sandIngot, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(sandPick), new Object[] { "XXX", " S ", " S ", 'X', Ingots.sandIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(sandAxe), new Object[] { "XX ", "XS ", " S ", 'X', Ingots.sandIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(sandShovel), new Object[] { "X", "S", "S", 'X', Ingots.sandIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(sandHoe), new Object[] { "XX ", " S ", " S ", 'X', Ingots.sandIngot, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(emeraldSword), new Object[] { "X", "X", "Z", 'X', Item.emerald, 'Z', Item.stick });
		GameRegistry.addRecipe(new ItemStack(emeraldPick), new Object[] { "XXX", " S ", " S ", 'X', Item.emerald, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(emeraldAxe), new Object[] { "XX ", "XS ", " S ", 'X', Item.emerald, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(emeraldShovel), new Object[] { "X", "S", "S", 'X', Item.emerald, 'S', Item.stick });
		GameRegistry.addRecipe(new ItemStack(emeraldHoe), new Object[] { "XX ", " S ", " S ", 'X', Item.emerald, 'S', Item.stick });
	}

}
