package hybridcraft.common.handlers;

public class IDHandler {
	
	//default item IDs
	//ingots and shards
	
	public static int OBSIDIAN_SHARD_DEFAULT = 500;
	public static int OBSIDIAN_INGOT_DEFAULT = 502;
	public static int SAND_INGOT_DEFAULT = 503;
	public static int DIRT_INGOT_DEFAULT = 504;
	
	//Default Tool IDs
		
	//dirt
	public static int DIRT_SWORD_DEFAULT = 505;
	public static int DIRT_PICK_DEFAULT = 506;
	public static int DIRT_AXE_DEFAULT = 507;
	public static int DIRT_SHOVEL_DEFAULT = 508;
	public static int DIRT_HOE_DEFAULT = 509;
	//dirt and stone
	public static int DIRTONE_SWORD_DEFAULT = 510;
	public static int DIRTONE_PICK_DEFAULTT = 511;
	public static int DIRTONE_AXE_DEFAULT = 512;
	public static int DIRTONE_SHOVEL_DEFAULT = 513;
	public static int DIRTONE_HOE_DEFAULT = 514;
	//dirt and iron
	public static int DIRON_SWORD_DEFAULT = 515;
	public static int DIRON_PICK_DEFAULT = 516;
	public static int DIRON_AXE_DEFAULT = 517;
	public static int DIRON_SHOVEL_DEFAULT = 518;
	public static int DIRON_HOE_DEFAULT = 519;
	//dirt and gold
	public static int DIROLD_SWORD_DEFAULT = 520;
	public static int DIROLD_PICK_DEFAULT = 521;
	public static int DIROLD_AXE_DEFAULT = 522;
	public static int DIROLD_SHOVEL_DEFAULT = 523;
	public static int DIROLD_HOE_DEFAULT = 524;
	//dirt and diamond
	public static int DIRMEND_SWORD_DEFAULT = 525;
	public static int DIRMEND_PICK_DEFAULT = 526;
	public static int DIRMEND_AXE_DEFAULT = 527;
	public static int DIRMEND_SHOVEL_DEFAULT = 528;
	public static int DIRMEND_HOE_DEFAULT = 529;
	//stone and iron
	public static int STORN_SWORD_DEFAULT = 530;
	public static int STORN_PICK_DEFAULT = 531;
	public static int STORN_AXE_DEFAULT = 532;
	public static int STORN_SHOVEL_DEFAULT = 533;
	public static int STORN_HOE_DEFAULT = 534;
	//stone and gold
	public static int STOLD_SWORD_DEFAULT = 535;
	public static int STOLD_PICK_DEFAULT = 536;
	public static int STOLD_AXE_DEFAULT = 537;
	public static int STOLD_SHOVEL_DEFAULT = 538;
	public static int STOLD_HOE_DEFAULT = 539;
	//stone and diamond
	public static int STOMEND_SWORD_DEFAULT = 540;
	public static int STOMEND_PICK_DEFAULT = 541;
	public static int STOMEND_AXE_DEFAULT = 542;
	public static int STOMEND_SHOVEL_DEFAULT = 543;
	public static int STOMEND_HOE_DEFAULT = 544;
	//iron and gold
	public static int IROLD_SWORD_DEFAULT = 545;
	public static int IROLD_PICK_DEFAULT = 546;
	public static int IROLD_AXE_DEFAULT = 547;
	public static int IROLD_SHOVEL_DEFAULT = 548;
	public static int IROLD_HOE_DEFAULT = 549;
	//iron and diamond
	public static int IRMEND_SWORD_DEFAULT = 550;
	public static int IRMEND_PICK_DEFAULT = 551;
	public static int IRMEND_AXE_DEFAULT = 552;
	public static int IRMEND_SHOVEL_DEFAULT = 553;
	public static int IRMEND_HOE_DEFAULT = 554;
	//gold and diamond
	public static int GOMEND_SWORD_DEFAULT = 555;
	public static int GOMEND_PICK_DEFAULT = 556;
	public static int GOMEND_AXE_DEFAULT = 557;
	public static int GOMEND_SHOVEL_DEFAULT = 558;
	public static int GOMEND_HOE_DEFAULT = 559;
	//sand
	public static int SAND_SWORD_DEFAULT = 555;
	public static int SAND_PICK_DEFAULT = 556;
	public static int SAND_AXE_DEFAULT = 557;
	public static int SAND_SHOVEL_DEFAULT = 558;
	public static int SAND_HOE_DEFAULT = 559;
	//obsidian
	public static int OBSIDIAN_SWORD_DEFAULT = 555;
	public static int OBSIDIAN_PICK_DEFAULT = 556;
	public static int OBSIDIAN_AXE_DEFAULT = 557;
	public static int OBSIDIAN_SHOVEL_DEFAULT = 558;
	public static int OBSIDIAN_HOE_DEFAULT = 559;
	//emerald
	public static int EMERALD_SWORD_DEFAULT = 555;
	public static int EMERALD_PICK_DEFAULT = 556;
	public static int EMERALD_AXE_DEFAULT = 557;
	public static int EMERALD_SHOVEL_DEFAULT = 558;
	public static int EMERALD_HOE_DEFAULT = 559;
	
	//food
	public static int BREAD_SLICE_DEFAULT = 560;
	public static int CHICKEN_STRIPS_DEFAULT = 561;
	public static int BEEF_SLICES_DEFAULT = 562;
	public static int BACON_DEFAULT = 563;
	public static int CHICKEN_SANDWICH_DEFAULT = 564;
	public static int CHICKEN_BACON_SANDWICH_DEFAULT = 565;
	public static int BEEF_SANDWICH_DEFAULT = 566;
	public static int BEEF_BACON_SANDWICH_DEFAULT = 567;
	public static int MEAT_SANDWICH_DEFAULT = 568;
	public static int APPLE_PIE_DEFAULT = 569;
	public static int FRUIT_SALAD_DEFAULT = 570;
	public static int APPLE_SLICE_DEFAULT = 571;
	public static int BAB_DEFAULT = 572;
	public static int PAB_DEFAULT = 573;
	public static int CAB_DEFAULT = 574;
	public static int DOG_BREAD_DEFAULT = 575;
	public static int BOWL_CHICKEN_DEFAULT = 576;
	public static int BOWL_BEEF_DEFAULT = 577;
	public static int BOWL_MEAT_DEFAULT = 578;
	public static int COUNTER_DEFAULT = 579;
	public static int STOVE_DEFAULT = 580;
	public static int POT_DEFAULT = 581;
	
	// Armors
	public static int DIRT_HELMET_DEFAULT = 582;
	public static int DIRT_PLATE_DEFAULT = 583;
	public static int DIRT_LEGS_DEFAULT = 584;
	public static int DIRT_BOOTS_DEFAULT = 585;
	public static int DIRTONE_HELMET_DEFAULT = 586;
	public static int DIRTONE_PLATE_DEFAULT = 587;
	public static int DIRTONE_LEGS_DEFAULT = 588;
	public static int DIRTONE_BOOTS_DEFAULT = 589;
	public static int DIRON_HELMET_DEFAULT = 590;
	public static int DIRON_PLATE_DEFAULT = 591;
	public static int DIRON_LEGS_DEFAULT = 592;
	public static int DIRON_BOOTS_DEFAULT = 593;
	public static int DIROLD_HELMET_DEFAULT = 594;
	public static int DIROLD_PLATE_DEFAULT = 595;
	public static int DIROLD_LEGS_DEFAULT = 596;
	public static int DIROLD_BOOTS_DEFAULT = 597;
	public static int DIRMEND_HELMET_DEFAULT = 598;
	public static int DIRMEND_PLATE_DEFAULT = 599;
	public static int DIRMEND_LEGS_DEFAULT = 600;
	public static int DIRMEND_BOOTS_DEFAULT = 601;
	public static int STORN_HELMET_DEFAULT = 602;
	public static int STORN_PLATE_DEFAULT = 603;
	public static int STORN_LEGS_DEFAULT = 604;
	public static int STORN_BOOTS_DEFAULT = 605;
	public static int STOLD_HELMET_DEFAULT = 606;
	public static int STOLD_PLATE_DEFAULT = 607;
	public static int STOLD_LEGS_DEFAULT = 608;
	public static int STOLD_BOOTS_DEFAULT = 609;
	public static int STOMEND_HELMET_DEFAULT = 610;
	public static int STOMEND_PLATE_DEFAULT = 611;
	public static int STOMEND_LEGS_DEFAULT = 612;
	public static int STOMEND_BOOTS_DEFAULT = 613;
	public static int IROLD_HELMET_DEFAULT = 614;
	public static int IROLD_PLATE_DEFAULT = 615;
	public static int IROLD_LEGS_DEFAULT = 616;
	public static int IROLD_BOOTS_DEFAULT = 617;
	public static int IRMEND_HELMET_DEFAULT = 618;
	public static int IRMEND_PLATE_DEFAULT = 619;
	public static int IRMEND_LEGS_DEFAULT = 620;
	public static int IRMEND_BOOTS_DEFAULT = 621;
	public static int GOMEND_HELMET_DEFAULT = 622;
	public static int GOMEND_PLATE_DEFAULT = 623;
	public static int GOMEND_LEGS_DEFAULT = 624;
	public static int GOMEND_BOOTS_DEFAULT = 625;
	public static int OBSIDIAN_HELMET_DEFAULT = 626;
	public static int OBSIDIAN_PLATE_DEFAULT = 627;
	public static int OBSIDIAN_LEGS_DEFAULT = 628;
	public static int OBSIDIAN_BOOTS_DEFAULT = 629;
	public static int DIRT_DEFAULT = 630;
	public static int DIRTONE_DEFAULT = 631;
	public static int DIRON_DEFAULT = 632;
	public static int DIROLD_DEFAULT = 633;
	public static int DIRMEND_DEFAULT = 634;
	public static int STONE_DEFAULT = 635;
	public static int STORN_DEFAULT = 636;
	public static int STOLD_DEFAULT = 637;
	public static int STOMEND_DEFAULT = 638;
	public static int IROLD_DEFAULT = 639;
	public static int IRMEND_DEFAULT = 640;
	public static int GOMEND_DEFAULT = 641;
	public static int DAND_DEFAULT = 642;
	public static int DAVEL_DEFAULT = 643;
	public static int DONE_DEFAULT = 644;
	public static int SAND_DEFAULT = 645;
	public static int STONE_HELMET_DEFAULT = 646;
	public static int STONE_PLATE_DEFAULT = 647;
	public static int STONE_LEGS_DEFAULT = 648;
	public static int STONE_BOOTS_DEFAULT = 649;
	public static int SAND_HELMET_DEFAULT = 650;
	public static int SAND_PLATE_DEFAULT = 651;
	public static int SAND_LEGS_DEFAULT = 652;
	public static int SAND_BOOTS_DEFAULT = 653;
	public static int EMERALD_HELMET_DEFAULT = 654;
	public static int EMERALD_PLATE_DEFAULT = 655;
	public static int EMERALD_LEGS_DEFAULT = 656;
	public static int EMERALD_BOOTS_DEFAULT = 657;
	public static int COMBINER_DEFAULT = 658;
	
	//Ingot IDs
	public static int OBSIDIAN_SHARD;
	public static int OBSIDIAN_INGOT;
	public static int SAND_INGOT;
	public static int DIRT_INGOT;
	
	//Tool IDs
	public static int DIRT_SWORD;
	public static int DIRT_PICK;
	public static int DIRT_AXE;
	public static int DIRT_SHOVEL;
	public static int DIRT_HOE;
	public static int DIRTONE_SWORD;
	public static int DIRTONE_PICK;
	public static int DIRTONE_AXE;
	public static int DIRTONE_SHOVEL;
	public static int DIRTONE_HOE;
	public static int DIRON_SWORD;
	public static int DIRON_PICK;
	public static int DIRON_AXE;
	public static int DIRON_SHOVEL;
	public static int DIRON_HOE;
	public static int DIROLD_SWORD;
	public static int DIROLD_PICK;
	public static int DIROLD_AXE;
	public static int DIROLD_SHOVEL;
	public static int DIROLD_HOE;
	public static int DIRMEND_SWORD;
	public static int DIRMEND_PICK;
	public static int DIRMEND_AXE;
	public static int DIRMEND_SHOVEL;
	public static int DIRMEND_HOE;
	public static int STORN_SWORD;
	public static int STORN_PICK;
	public static int STORN_AXE;
	public static int STORN_SHOVEL;
	public static int STORN_HOE;
	public static int STOLD_SWORD;
	public static int STOLD_PICK;
	public static int STOLD_AXE;
	public static int STOLD_SHOVEL;
	public static int STOLD_HOE;
	public static int STOMEND_SWORD;
	public static int STOMEND_PICK;
	public static int STOMEND_AXE;
	public static int STOMEND_SHOVEL;
	public static int STOMEND_HOE;
	public static int IROLD_SWORD;
	public static int IROLD_PICK;
	public static int IROLD_AXE;
	public static int IROLD_SHOVEL;
	public static int IROLD_HOE;
	public static int IRMEND_SWORD;
	public static int IRMEND_PICK;
	public static int IRMEND_AXE;
	public static int IRMEND_SHOVEL;
	public static int IRMEND_HOE;
	public static int GOMEND_SWORD;
	public static int GOMEND_PICK;
	public static int GOMEND_AXE;
	public static int GOMEND_SHOVEL;
	public static int GOMEND_HOE;
	public static int OBSIDIAN_SWORD;
	public static int OBSIDIAN_PICK;
	public static int OBSIDIAN_AXE;
	public static int OBSIDIAN_SHOVEL;
	public static int OBSIDIAN_HOE;
	public static int EMERALD_SWORD;
	public static int EMERALD_PICK;
	public static int EMERALD_AXE;
	public static int EMERALD_SHOVEL;
	public static int EMERALD_HOE;
	public static int SAND_SWORD;
	public static int SAND_PICK;
	public static int SAND_AXE;
	public static int SAND_SHOVEL;
	public static int SAND_HOE;
	
	// Food
	public static int  breadSliceID;
	public static int  chickenStripsID;
	public static int  beefSlicesID;
	public static int  baconID;
	public static int  chickenSandwichID;
	public static int  chickenSandwichBaconID;
	public static int  beefSandwichID;
	public static int  beefSandwichBaconID;
	public static int  meatSandwichID;
	public static int  applePieID;
	public static int  fruitSaladID;
	public static int  appleSliceID;
	public static int  counterID;
	public static int  stoveID;
	public static int  potID;
	public static int  bowlChickenID;
	public static int  bowlBeefID;
	public static int  bowlMeatID;
	public static int  BaBID;
	public static int  PaBID;
	public static int  CaBID;
	public static int  DogBreadID;

	public static int  dirtHelmetID;
	public static int  dirtPlateID;
	public static int  dirtLegsID;
	public static int  dirtBootsID;
	public static int  dirtoneHelmetID;
	public static int  dirtonePlateID;
	public static int  dirtoneLegsID;
	public static int  dirtoneBootsID;
	public static int  dironHelmetID;
	public static int  dironPlateID;
	public static int  dironLegsID;
	public static int  dironBootsID;
	public static int  diroldHelmetID;
	public static int  diroldPlateID;
	public static int  diroldLegsID;
	public static int  diroldBootsID;
	public static int  dirmendHelmetID;
	public static int  dirmendPlateID;
	public static int  dirmendLegsID;
	public static int  dirmendBootsID;
	public static int  stornHelmetID;
	public static int  stornPlateID;
	public static int  stornLegsID;
	public static int  stornBootsID;
	public static int  stoldHelmetID;
	public static int  stoldPlateID;
	public static int  stoldLegsID;
	public static int  stoldBootsID;
	public static int  stomendHelmetID;
	public static int  stomendPlateID;
	public static int  stomendLegsID;
	public static int  stomendBootsID;
	public static int  iroldHelmetID;
	public static int  iroldPlateID;
	public static int  iroldLegsID;
	public static int  iroldBootsID;
	public static int  irmendHelmetID;
	public static int  irmendPlateID;
	public static int  irmendLegsID;
	public static int  irmendBootsID;
	public static int  gomendHelmetID;
	public static int  gomendPlateID;
	public static int  gomendLegsID;
	public static int  gomendBootsID;
	public static int  obsidianHelmetID;
	public static int  obsidianPlateID;
	public static int  obsidianLegsID;
	public static int  obsidianBootsID;
	public static int  dirtBlockID;
	public static int  dirtoneBlockID;
	public static int  dironBlockID;
	public static int  diroldBlockID;
	public static int  dirmendBlockID;
	public static int  stoneBlockID;
	public static int  stornBlockID;
	public static int  stoldBlockID;
	public static int  stomendBlockID;
	public static int  iroldBlockID;
	public static int  irmendBlockID;
	public static int  gomendBlockID;
	public static int  dandID;
	public static int  davelID;
	public static int  doneID;
	public static int  dirtFlowerID;
	public static int  stoneFlowerID;
	public static int  ironFlowerID;
	public static int  goldFlowerID;
	public static int  diamondFlowerID;
	public static int  obsidianFlowerID;
	public static int  sandBlockID;
	public static int  stoneHelmetID;
	public static int  stonePlateID;
	public static int  stoneLegsID;
	public static int  stoneBootsID;
	public static int  sandHelmetID;
	public static int  sandPlateID;
	public static int  sandLegsID;
	public static int  sandBootsID;
	public static int  emeraldhelmetID;
	public static int  emeraldplateID;
	public static int  emeraldlegsID;
	public static int  emeraldbootsID;
	public static int  combinerID;
	
}
