package hybridcraft.common.mod.lib;

import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import hybridcraft.common.handlers.ConfigHandler;

public class Configuration {
	
	public static final String CATEGORY_TOOL = "tools";
	public static final String CATEGORY_INGOT = "ingots";
	public static final String CATEGORY_ARMOR = "armors";
	public static final String CATEGORY_FLOWER = "flowers";
	public static final String CATEGORY_BLOCK = "blocks";

	public static int  dirtHelmetID;
	public static int  dirtPlateID;
	public static int  dirtLegsID;
	public static int  dirtBootsID;
	public static int  dirtoneHelmetID;
	public static int  dirtonePlateID;
	public static int  dirtoneLegsID;
	public static int  dirtoneBootsID;
	public static int  dironHelmetID;
	public static int  dironPlateID;
	public static int  dironLegsID;
	public static int  dironBootsID;
	public static int  diroldHelmetID;
	public static int  diroldPlateID;
	public static int  diroldLegsID;
	public static int  diroldBootsID;
	public static int  dirmendHelmetID;
	public static int  dirmendPlateID;
	public static int  dirmendLegsID;
	public static int  dirmendBootsID;
	public static int  stornHelmetID;
	public static int  stornPlateID;
	public static int  stornLegsID;
	public static int  stornBootsID;
	public static int  stoldHelmetID;
	public static int  stoldPlateID;
	public static int  stoldLegsID;
	public static int  stoldBootsID;
	public static int  stomendHelmetID;
	public static int  stomendPlateID;
	public static int  stomendLegsID;
	public static int  stomendBootsID;
	public static int  iroldHelmetID;
	public static int  iroldPlateID;
	public static int  iroldLegsID;
	public static int  iroldBootsID;
	public static int  irmendHelmetID;
	public static int  irmendPlateID;
	public static int  irmendLegsID;
	public static int  irmendBootsID;
	public static int  gomendHelmetID;
	public static int  gomendPlateID;
	public static int  gomendLegsID;
	public static int  gomendBootsID;
	public static int  obsidianHelmetID;
	public static int  obsidianPlateID;
	public static int  obsidianLegsID;
	public static int  obsidianBootsID;
	public static int  dirtBlockID;
	public static int  dirtoneBlockID;
	public static int  dironBlockID;
	public static int  diroldBlockID;
	public static int  dirmendBlockID;
	public static int  stoneBlockID;
	public static int  stornBlockID;
	public static int  stoldBlockID;
	public static int  stomendBlockID;
	public static int  iroldBlockID;
	public static int  irmendBlockID;
	public static int  gomendBlockID;
	public static int  dandID;
	public static int  davelID;
	public static int  doneID;
	public static int  dirtFlowerID;
	public static int  stoneFlowerID;
	public static int  ironFlowerID;
	public static int  goldFlowerID;
	public static int  diamondFlowerID;
	public static int  obsidianFlowerID;
	public static int  sandBlockID;
	public static int  stoneHelmetID;
	public static int  stonePlateID;
	public static int  stoneLegsID;
	public static int  stoneBootsID;
	public static int  sandHelmetID;
	public static int  sandPlateID;
	public static int  sandLegsID;
	public static int  sandBootsID;
	public static int  emeraldhelmetID;
	public static int  emeraldplateID;
	public static int  emeraldlegsID;
	public static int  emeraldbootsID;
	public static int  combinerID;
	
	
	
	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
	
	ConfigHandler config =  new ConfigHandler(event.getSuggestedConfigurationFile());
	
	config.loadConfig();
	config.getInstance().load();
	
	dirtHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Dirt Helmet ", 564).getInt();
	dirtPlateID = config.getInstance().get(CATEGORY_ARMOR, "Dirt Chestplate", 565).getInt();
	dirtLegsID = config.getInstance().get(CATEGORY_ARMOR, "Dirt Leggings", 566).getInt();
	dirtBootsID = config.getInstance().get(CATEGORY_ARMOR, "Dirt Boots", 567).getInt();
	dirtoneHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Dirtone Helmet", 568).getInt();
	dirtonePlateID = config.getInstance().get(CATEGORY_ARMOR, "Dirtone Chestplate", 569).getInt();
	dirtoneLegsID = config.getInstance().get(CATEGORY_ARMOR, "Dirtone Leggings", 570).getInt();
	dirtoneBootsID = config.getInstance().get(CATEGORY_ARMOR, "Dirtone Boots", 571).getInt();
	dironHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Diron Helmet", 572).getInt();
	dironPlateID = config.getInstance().get(CATEGORY_ARMOR, "Diron Chestplate", 573).getInt();
	dironLegsID = config.getInstance().get(CATEGORY_ARMOR, "Diron Leggings", 574).getInt();
	dironBootsID = config.getInstance().get(CATEGORY_ARMOR, "Diron Boots", 575).getInt();
	diroldHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Dirold Helmet", 576).getInt();
	diroldPlateID = config.getInstance().get(CATEGORY_ARMOR, "Dirold Chestplate", 577).getInt();
	diroldLegsID = config.getInstance().get(CATEGORY_ARMOR, "Dirold Leggings", 578).getInt();
	diroldBootsID = config.getInstance().get(CATEGORY_ARMOR, "Dirold Boots", 579).getInt();
	dirmendHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Dirmend Helmet", 580).getInt();
	dirmendPlateID = config.getInstance().get(CATEGORY_ARMOR, "Dirmend Chestplate", 581).getInt();
	dirmendLegsID = config.getInstance().get(CATEGORY_ARMOR, "Dirmend Leggings", 582).getInt();
	dirmendBootsID = config.getInstance().get(CATEGORY_ARMOR, "Dirmend Boots", 583).getInt();
	stornHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Storn Helmet", 584).getInt();
	stornPlateID = config.getInstance().get(CATEGORY_ARMOR, "Storn Chestplate", 585).getInt();
	stornLegsID = config.getInstance().get(CATEGORY_ARMOR, "Storn Leggings", 586).getInt();
	stornBootsID = config.getInstance().get(CATEGORY_ARMOR, "Storn Boots", 587).getInt();
	stoldHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Stold Helmet", 588).getInt();
	stoldPlateID = config.getInstance().get(CATEGORY_ARMOR, "Stold Chestplate", 589).getInt();
	stoldLegsID = config.getInstance().get(CATEGORY_ARMOR, "Stold Leggings", 590).getInt();
	stoldBootsID = config.getInstance().get(CATEGORY_ARMOR, "Stold Boots", 591).getInt();
	stomendHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Stomend Helmet", 592).getInt();
	stomendPlateID = config.getInstance().get(CATEGORY_ARMOR, "Stomend Chestplate", 593).getInt();
	stomendLegsID = config.getInstance().get(CATEGORY_ARMOR, "Stomend Leggings", 594).getInt();
	stomendBootsID = config.getInstance().get(CATEGORY_ARMOR, "Stomend Boots", 595).getInt();
	iroldHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Irold Helmet", 596).getInt();
	iroldPlateID = config.getInstance().get(CATEGORY_ARMOR, "Irold Chestplate", 597).getInt();
	iroldLegsID = config.getInstance().get(CATEGORY_ARMOR, "Irold Leggings", 598).getInt();
	iroldBootsID = config.getInstance().get(CATEGORY_ARMOR, "Irold Boots", 599).getInt();
	irmendHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Irmend Helmet", 600).getInt();
	irmendPlateID = config.getInstance().get(CATEGORY_ARMOR, "Irmend Chestplate", 601).getInt();
	irmendLegsID = config.getInstance().get(CATEGORY_ARMOR, "Irmend Leggings", 602).getInt();
	irmendBootsID = config.getInstance().get(CATEGORY_ARMOR, "Irmend Boots", 603).getInt();
	gomendHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Gomend Helmet", 604).getInt();
	gomendPlateID = config.getInstance().get(CATEGORY_ARMOR, "Gomend Chestplate", 605).getInt();
	gomendLegsID = config.getInstance().get(CATEGORY_ARMOR, "Gomend Leggings", 606).getInt();
	gomendBootsID = config.getInstance().get(CATEGORY_ARMOR, "Gomend Boots", 607).getInt();
	obsidianHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Obsidian Helmet", 608).getInt();
	obsidianPlateID = config.getInstance().get(CATEGORY_ARMOR, "Obsidian Chestplate", 609).getInt();
	obsidianLegsID = config.getInstance().get(CATEGORY_ARMOR, "Obsidian Leggings", 610).getInt();
	obsidianBootsID = config.getInstance().get(CATEGORY_ARMOR, "Obsidian Boots", 611).getInt();
	dirtBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Dirt Ingot Block", 612).getInt();
	dirtoneBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Dirtone Ingot Block", 613).getInt();
	dironBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Diron Ingot Block", 614).getInt();
	diroldBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Dirold Ingot Block", 615).getInt();
	dirmendBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Dirmend Ingot Block", 616).getInt();
	stoneBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK,	"Stone Ingot Block", 617).getInt();
	stornBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK,	"Storn Ingot Block", 618).getInt();
	stoldBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK,	"Stold Ingot Block", 619).getInt();
	stomendBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Stomend Ingot Block", 620).getInt();
	iroldBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK,	"Irold Ingot Block", 621).getInt();
	irmendBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Irmend Ingot Block", 622).getInt();
	gomendBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Gomend Ingot Block", 623).getInt();
	dandID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Dirt/Sand Block", 624).getInt();
	davelID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Dirt/Gravel Block",	625).getInt();
	doneID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Dirt/Stone Block", 626).getInt();
	sandBlockID = config.getInstance().get(Configuration.CATEGORY_BLOCK, "Sand Ingot Block", 633).getInt();
	stoneHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Stone Helmet", 634).getInt();
	stonePlateID = config.getInstance().get(CATEGORY_ARMOR, "Stone Chestplate", 635).getInt();
	stoneLegsID = config.getInstance().get(CATEGORY_ARMOR, "Stone Leggings", 636).getInt();
	stoneBootsID = config.getInstance().get(CATEGORY_ARMOR, "Stone Boots", 637).getInt();
	sandHelmetID = config.getInstance().get(CATEGORY_ARMOR, "Sand Helmet", 638).getInt();
	sandPlateID = config.getInstance().get(CATEGORY_ARMOR, "Sand Chestplate", 639).getInt();
	sandLegsID = config.getInstance().get(CATEGORY_ARMOR, "Sand Leggings", 640).getInt();
	sandBootsID = config.getInstance().get(CATEGORY_ARMOR, "Sand Boots", 641).getInt();
	emeraldhelmetID = config.getInstance().get(CATEGORY_ARMOR, "Emerald Helmet", 659).getInt();
	emeraldplateID = config.getInstance().get(CATEGORY_ARMOR, "Emerald Chestplate", 660).getInt();
	emeraldlegsID = config.getInstance().get(CATEGORY_ARMOR, "Emerald Leggings", 661).getInt();
	emeraldbootsID = config.getInstance().get(CATEGORY_ARMOR, "Emerald Boots", 662).getInt();
	combinerID = config.getInstance().get(CATEGORY_ARMOR, "Combiner", 663).getInt();
	
	config.getInstance().save();
}

}
